# Generated by Django 5.1 on 2024-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
