# Generated by Django 5.1 on 2024-09-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
